// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfc-8jKM7_VG_Seqw5xUNd1SC2bTHSFJs',
    appId: '1:309976053778:web:2b8c9b9e4541dd250600cb',
    messagingSenderId: '309976053778',
    projectId: 'repozytorium-binarne',
    authDomain: 'repozytorium-binarne.firebaseapp.com',
    storageBucket: 'repozytorium-binarne.firebasestorage.app',
    measurementId: 'G-LFG9TDS9ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF2VHeY85ZmiTtN8L_ptn8Hf5t5vf1gjU',
    appId: '1:309976053778:android:de6a09726c6205d10600cb',
    messagingSenderId: '309976053778',
    projectId: 'repozytorium-binarne',
    storageBucket: 'repozytorium-binarne.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2p8fr9BK25rzoqk2NB8oGu_nJVleogBI',
    appId: '1:309976053778:ios:1b02c6b2a7a2d39c0600cb',
    messagingSenderId: '309976053778',
    projectId: 'repozytorium-binarne',
    storageBucket: 'repozytorium-binarne.firebasestorage.app',
    iosBundleId: 'com.example.repoBinarne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2p8fr9BK25rzoqk2NB8oGu_nJVleogBI',
    appId: '1:309976053778:ios:1b02c6b2a7a2d39c0600cb',
    messagingSenderId: '309976053778',
    projectId: 'repozytorium-binarne',
    storageBucket: 'repozytorium-binarne.firebasestorage.app',
    iosBundleId: 'com.example.repoBinarne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfc-8jKM7_VG_Seqw5xUNd1SC2bTHSFJs',
    appId: '1:309976053778:web:5b4209dc52b8a48e0600cb',
    messagingSenderId: '309976053778',
    projectId: 'repozytorium-binarne',
    authDomain: 'repozytorium-binarne.firebaseapp.com',
    storageBucket: 'repozytorium-binarne.firebasestorage.app',
    measurementId: 'G-RX55XKY1GW',
  );
}
